import { createHmac, randomBytes, timingSafeEqual } from 'node:crypto';
import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException, ServiceUnavailableException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import Razorpay from 'razorpay';
import { Prisma, type PaymentStatus } from '../../generated/prisma/client';
import { PrismaService } from '../../database/prisma.service';
import type { VerifyRazorpayPaymentDto } from './dto/verify-razorpay-payment.dto';

@Injectable()
export class RazorpayService {
  private readonly keyId:string|null;private readonly keySecret:string|null;private readonly webhookSecret:string|null;private readonly client:Razorpay|null;private readonly mock:boolean;private readonly mockRefundFailureAmount:number|null;
  constructor(private readonly prisma:PrismaService,config:ConfigService){this.keyId=config.get<string>('RAZORPAY_KEY_ID')||null;this.keySecret=config.get<string>('RAZORPAY_KEY_SECRET')||null;this.webhookSecret=config.get<string>('RAZORPAY_WEBHOOK_SECRET')||null;this.mock=config.get('NODE_ENV')==='test'&&config.get('RAZORPAY_MOCK_MODE')==='true';const failure=Number(config.get<string>('RAZORPAY_MOCK_REFUND_FAILURE_AMOUNT'));this.mockRefundFailureAmount=Number.isSafeInteger(failure)&&failure>0?failure:null;this.client=!this.mock&&this.keyId&&this.keySecret?new Razorpay({key_id:this.keyId,key_secret:this.keySecret}):null;}
  async create(userId:string,orderId:string){const order=await this.prisma.order.findFirst({where:{id:orderId,userId},include:{payments:true}});if(!order)throw new NotFoundException('Order not found');if(order.status!=='PENDING')throw new BadRequestException('Order is not awaiting payment');if(!order.reservationExpiresAt||order.reservationExpiresAt<=new Date())throw new ConflictException('Order reservation has expired');const current=order.payments[0];if(current?.providerOrderId&&current.status==='PENDING')return this.checkout(order,current.providerOrderId);let providerOrderId:string;if(this.mock)providerOrderId=`order_${randomBytes(12).toString('hex')}`;else{const client=this.requireClient();try{const providerOrder=await client.orders.create({amount:order.totalPaise,currency:'INR',receipt:order.orderNumber.slice(0,40),notes:{internalOrderId:order.id}});providerOrderId=providerOrder.id;}catch{throw new ServiceUnavailableException('Payment service is unavailable');}}await this.prisma.payment.upsert({where:{orderId},update:{provider:'RAZORPAY',providerOrderId,status:'PENDING',amountPaise:order.totalPaise},create:{orderId,provider:'RAZORPAY',providerOrderId,status:'PENDING',amountPaise:order.totalPaise}});return this.checkout(order,providerOrderId);}
  async verify(userId:string,dto:VerifyRazorpayPaymentDto){const payment=await this.prisma.payment.findUnique({where:{orderId:dto.orderId},include:{order:true}});if(!payment||payment.order.userId!==userId)throw new NotFoundException('Payment not found');if(payment.providerOrderId!==dto.razorpay_order_id)throw new BadRequestException('Payment could not be verified');this.assertSignature(`${dto.razorpay_order_id}|${dto.razorpay_payment_id}`,dto.razorpay_signature,this.requireSecret());let amount=payment.amountPaise,status='captured',providerOrderId=dto.razorpay_order_id;if(!this.mock){try{const entity=await this.requireClient().payments.fetch(dto.razorpay_payment_id);amount=Number(entity.amount);status=entity.status;providerOrderId=String(entity.order_id);}catch{throw new BadRequestException('Payment could not be verified');}}if(status!=='captured'||providerOrderId!==payment.providerOrderId||amount!==payment.order.totalPaise)throw new BadRequestException('Payment could not be verified');return this.confirm(payment.id,dto.razorpay_payment_id,amount);}
  async webhook(raw:Buffer|undefined,signature:string|undefined,payload:unknown){if(!raw||!signature||!this.webhookSecret)throw new ForbiddenException('Invalid webhook signature');this.assertSignature(raw,signature,this.webhookSecret);const event=payload as {event?:string;payload?:{payment?:{entity?:{id?:string;order_id?:string;amount?:number;status?:string}}}};const entity=event.payload?.payment?.entity;if(event.event!=='payment.captured'||!entity?.id||!entity.order_id||entity.status!=='captured')return{status:'ignored' as const};const payment=await this.prisma.payment.findFirst({where:{providerOrderId:entity.order_id},include:{order:true}});if(!payment)return{status:'ignored' as const};if(entity.amount!==payment.order.totalPaise)throw new BadRequestException('Payment amount mismatch');await this.confirm(payment.id,entity.id,entity.amount);return{status:'ok' as const};}
  async status(userId:string,orderId:string){const order=await this.prisma.order.findFirst({where:{id:orderId,userId},include:{payments:{select:{status:true,provider:true}}}});if(!order)throw new NotFoundException('Order not found');return{paymentStatus:order.payments[0]?.status??'PENDING',provider:order.payments[0]?.provider??null,orderStatus:order.status};}
  async refundProviderPayment(providerPaymentId:string,amountPaise:number,internalRefundId:string){if(this.mock){if(amountPaise===this.mockRefundFailureAmount)throw new ServiceUnavailableException('Refund service is unavailable');return{id:`rfnd_${randomBytes(12).toString('hex')}`,amount:amountPaise,status:'processed'};}try{const refund=await this.requireClient().payments.refund(providerPaymentId,{amount:amountPaise,notes:{internalRefundId}});return{id:String(refund.id),amount:Number(refund.amount),status:String(refund.status)};}catch{throw new ServiceUnavailableException('Refund service is unavailable');}}
  async fetchProviderPayment(providerPaymentId:string){if(this.mock)return{id:providerPaymentId,status:'captured',amount:null as number|null,orderId:null as string|null};try{const entity=await this.requireClient().payments.fetch(providerPaymentId);return{id:String(entity.id),status:String(entity.status),amount:Number(entity.amount),orderId:entity.order_id?String(entity.order_id):null};}catch{throw new ServiceUnavailableException('Payment service is unavailable');}}
  async reconcilePayment(paymentId:string){const payment=await this.prisma.payment.findUnique({where:{id:paymentId},include:{order:true}});if(!payment)throw new NotFoundException('Payment not found');if(payment.status==='PAID'||payment.status==='PARTIALLY_REFUNDED'||payment.status==='REFUNDED')return{changed:false,paymentStatus:payment.status,orderStatus:payment.order.status};if(!payment.providerPaymentId)throw new ConflictException('Provider payment ID is unavailable');const provider=await this.fetchProviderPayment(payment.providerPaymentId);const amount=provider.amount??payment.amountPaise,providerOrderId=provider.orderId??payment.providerOrderId;if(provider.status!=='captured'||amount!==payment.amountPaise||amount!==payment.order.totalPaise||providerOrderId!==payment.providerOrderId)throw new ConflictException('Provider payment is not a matching captured payment');const result=await this.confirm(payment.id,payment.providerPaymentId,amount);return{changed:true,...result};}
  private async confirm(paymentId:string,providerPaymentId:string,amount:number){return this.prisma.$transaction(async tx=>{const payment=await tx.payment.findUniqueOrThrow({where:{id:paymentId},include:{order:{include:{inventoryReservations:{where:{releasedAt:null}}}}}});if(payment.status==='PAID'&&payment.order.status==='CONFIRMED')return{paymentStatus:'PAID' as PaymentStatus,orderStatus:'CONFIRMED' as const,orderId:payment.orderId,amountPaidPaise:payment.amountPaise};if(payment.order.status!=='PENDING'||!payment.order.reservationExpiresAt||payment.order.reservationExpiresAt<=new Date())throw new ConflictException('Order reservation has expired');if(payment.amountPaise!==amount||payment.order.totalPaise!==amount)throw new BadRequestException('Payment amount mismatch');for(const reservation of payment.order.inventoryReservations){const changed=await tx.$executeRaw`UPDATE "Inventory" SET "stockQuantity"="stockQuantity"-${reservation.quantity},"reservedQuantity"="reservedQuantity"-${reservation.quantity} WHERE "variantId"=${reservation.variantId}::uuid AND "stockQuantity">=${reservation.quantity} AND "reservedQuantity">=${reservation.quantity}`;if(changed!==1)throw new ConflictException('Reserved inventory is unavailable');await tx.inventoryReservation.updateMany({where:{id:reservation.id,releasedAt:null},data:{releasedAt:new Date()}});}await tx.payment.update({where:{id:payment.id},data:{providerPaymentId,status:'PAID'}});await tx.order.update({where:{id:payment.orderId},data:{status:'CONFIRMED'}});return{paymentStatus:'PAID' as PaymentStatus,orderStatus:'CONFIRMED' as const,orderId:payment.orderId,amountPaidPaise:amount};},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
  private checkout(order:{id:string;totalPaise:number;orderNumber:string},providerOrderId:string){return{internalOrderId:order.id,providerOrderId,amountPaise:order.totalPaise,currency:'INR',keyId:this.mock?'rzp_test_mock':this.keyId,orderNumber:order.orderNumber};}
  private assertSignature(data:string|Buffer,received:string,secret:string){const expected=createHmac('sha256',secret).update(data).digest('hex');const a=Buffer.from(expected),b=Buffer.from(received);if(a.length!==b.length||!timingSafeEqual(a,b))throw new BadRequestException('Payment could not be verified');}
  private requireSecret(){if(this.mock)return'test_key_secret';if(!this.keySecret)throw new ServiceUnavailableException('Payment service is not configured');return this.keySecret;}
  private requireClient(){if(!this.client)throw new ServiceUnavailableException('Payment service is not configured');return this.client;}
}
