CREATE TYPE "ReviewStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED');

ALTER TABLE "Address" ADD COLUMN "latitude" DECIMAL(9,6), ADD COLUMN "longitude" DECIMAL(9,6), ADD COLUMN "locationProvider" TEXT, ADD COLUMN "providerPlaceId" TEXT, ADD COLUMN "formattedAddress" TEXT;
ALTER TABLE "Address" ADD CONSTRAINT "Address_coordinates_check" CHECK (("latitude" IS NULL AND "longitude" IS NULL) OR ("latitude" BETWEEN -90 AND 90 AND "longitude" BETWEEN -180 AND 180));
ALTER TABLE "Order" ADD COLUMN "shippingLatitude" DECIMAL(9,6), ADD COLUMN "shippingLongitude" DECIMAL(9,6), ADD COLUMN "shippingLocationProvider" TEXT, ADD COLUMN "shippingProviderPlaceId" TEXT, ADD COLUMN "shippingFormattedAddress" TEXT;
ALTER TABLE "Order" ADD CONSTRAINT "Order_shipping_coordinates_check" CHECK (("shippingLatitude" IS NULL AND "shippingLongitude" IS NULL) OR ("shippingLatitude" BETWEEN -90 AND 90 AND "shippingLongitude" BETWEEN -180 AND 180));

CREATE TABLE "ProductReview" ("id" UUID NOT NULL,"productId" UUID NOT NULL,"userId" UUID NOT NULL,"rating" INTEGER NOT NULL,"title" TEXT,"body" TEXT,"status" "ReviewStatus" NOT NULL DEFAULT 'PENDING',"verifiedPurchase" BOOLEAN NOT NULL DEFAULT false,"moderationReason" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,"deletedAt" TIMESTAMP(3),CONSTRAINT "ProductReview_pkey" PRIMARY KEY("id"),CONSTRAINT "ProductReview_rating_check" CHECK("rating" BETWEEN 1 AND 5),CONSTRAINT "ProductReview_productId_fkey" FOREIGN KEY("productId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE,CONSTRAINT "ProductReview_userId_fkey" FOREIGN KEY("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE UNIQUE INDEX "ProductReview_one_active_per_user_product" ON "ProductReview"("userId","productId") WHERE "deletedAt" IS NULL;
CREATE INDEX "ProductReview_productId_status_createdAt_idx" ON "ProductReview"("productId","status","createdAt"); CREATE INDEX "ProductReview_userId_createdAt_idx" ON "ProductReview"("userId","createdAt"); CREATE INDEX "ProductReview_rating_idx" ON "ProductReview"("rating");

CREATE TABLE "ProductReviewMedia" ("id" UUID NOT NULL,"reviewId" UUID NOT NULL,"imageKitFileId" TEXT NOT NULL,"url" TEXT NOT NULL,"width" INTEGER,"height" INTEGER,"mimeType" TEXT NOT NULL,"sizeBytes" INTEGER NOT NULL,"sortOrder" INTEGER NOT NULL DEFAULT 0,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ProductReviewMedia_pkey" PRIMARY KEY("id"),CONSTRAINT "ProductReviewMedia_metadata_check" CHECK("sizeBytes">0 AND "sortOrder">=0 AND ("width" IS NULL OR "width">0) AND ("height" IS NULL OR "height">0)),CONSTRAINT "ProductReviewMedia_reviewId_fkey" FOREIGN KEY("reviewId") REFERENCES "ProductReview"("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE UNIQUE INDEX "ProductReviewMedia_imageKitFileId_key" ON "ProductReviewMedia"("imageKitFileId"); CREATE INDEX "ProductReviewMedia_reviewId_sortOrder_idx" ON "ProductReviewMedia"("reviewId","sortOrder");

CREATE TABLE "ProductReviewStats" ("productId" UUID NOT NULL,"reviewCount" INTEGER NOT NULL DEFAULT 0,"ratingSum" INTEGER NOT NULL DEFAULT 0,"star1Count" INTEGER NOT NULL DEFAULT 0,"star2Count" INTEGER NOT NULL DEFAULT 0,"star3Count" INTEGER NOT NULL DEFAULT 0,"star4Count" INTEGER NOT NULL DEFAULT 0,"star5Count" INTEGER NOT NULL DEFAULT 0,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "ProductReviewStats_pkey" PRIMARY KEY("productId"),CONSTRAINT "ProductReviewStats_nonnegative_check" CHECK("reviewCount">=0 AND "ratingSum">=0 AND "star1Count">=0 AND "star2Count">=0 AND "star3Count">=0 AND "star4Count">=0 AND "star5Count">=0),CONSTRAINT "ProductReviewStats_productId_fkey" FOREIGN KEY("productId") REFERENCES "Product"("id") ON DELETE CASCADE ON UPDATE CASCADE);
