'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import { ProductImage } from '@/components/catalog/product-image';
import { useAuth } from '@/features/auth/auth-provider';
import { useCart } from '@/features/cart/cart-provider';
import { formatINR } from '@/lib/format-money';
const value=(input:unknown)=>typeof input==='string'||typeof input==='number'||typeof input==='boolean'?String(input):JSON.stringify(input);
export default function CartPage(){const router=useRouter();const {user,isAuthenticated,isLoading:authLoading}=useAuth();const {cart,isLoading,update,remove,clear,setMode}=useCart();const [error,setError]=useState<string|null>(null);useEffect(()=>{if(!authLoading&&!isAuthenticated)router.replace('/login');},[authLoading,isAuthenticated,router]);
  const act=async(action:()=>Promise<void>)=>{setError(null);try{await action();}catch(caught){setError(caught instanceof Error?caught.message:'Unable to update cart.');}};
  if(authLoading||!user||!cart)return <main className="mx-auto max-w-6xl px-4 py-16"><p>{authLoading?'Restoring your session…':'Loading cart…'}</p></main>;
  const wholesale=user.accountType==='WHOLESALE'&&user.wholesaleStatus==='APPROVED';
  return <main className="mx-auto min-h-[70vh] max-w-6xl px-4 py-12 sm:px-6 lg:px-8"><div className="flex items-end justify-between"><div><h1 className="text-4xl font-bold">Your cart</h1><p className="mt-2 text-slate-600">{cart.itemCount} item{cart.itemCount===1?'':'s'}</p></div>{cart.items.length>0&&<button className="text-sm font-semibold text-red-700" disabled={isLoading} onClick={()=>void act(clear)}>Clear cart</button>}</div>
  <section className="mt-8 rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">Pricing mode</h2><div className="mt-3 flex gap-3"><button className={`secondary-button ${cart.pricingMode==='RETAIL'?'border-blue-700 bg-blue-50':''}`} disabled={isLoading} onClick={()=>void act(()=>setMode('RETAIL'))}>Retail</button>{wholesale&&<button className={`secondary-button ${cart.pricingMode==='WHOLESALE'?'border-blue-700 bg-blue-50':''}`} disabled={isLoading} onClick={()=>void act(()=>setMode('WHOLESALE'))}>Wholesale</button>}</div>{!wholesale&&<p className="mt-3 text-sm text-slate-600">Wholesale pricing is available to approved wholesale accounts.</p>}{error&&<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}</section>
  {cart.items.length===0?<div className="mt-8 rounded-2xl border border-dashed border-slate-300 bg-white py-20 text-center"><h2 className="text-2xl font-semibold">Your cart is empty.</h2><Link href="/products" className="primary-button mt-6 w-auto">Continue Shopping</Link></div>:<><div className="mt-8 space-y-4">{cart.items.map((item)=><article key={item.cartItemId} className="grid gap-4 rounded-2xl border border-slate-200 bg-white p-4 sm:grid-cols-[8rem_1fr_auto]"><Link href={`/products/${item.productSlug}`} className="relative aspect-square overflow-hidden rounded-xl bg-slate-100"><ProductImage src={item.image?.url} alt={item.image?.altText||item.productName} sizes="128px"/></Link><div><Link href={`/products/${item.productSlug}`} className="font-semibold hover:text-blue-700">{item.productName}</Link><p className="mt-1 text-sm text-slate-600">{item.variantName}</p><dl className="mt-2 flex flex-wrap gap-x-3 text-sm text-slate-600">{Object.entries(item.attributes).map(([key,input])=><div key={key}><dt className="inline capitalize">{key}: </dt><dd className="inline">{value(input)}</dd></div>)}</dl><p className="mt-3">{formatINR(item.unitPricePaise)} each</p><p className={`mt-1 text-sm ${item.isAvailable?'text-emerald-700':'text-red-700'}`}>{item.isAvailable?'Available':'Insufficient current stock'}</p><div className="mt-4 flex items-center gap-3"><button aria-label={`Decrease ${item.productName} quantity`} className="secondary-button h-10 w-10 p-0" disabled={isLoading||item.quantity<=1} onClick={()=>void act(()=>update(item.cartItemId,item.quantity-1))}>−</button><span className="min-w-8 text-center" aria-live="polite">{item.quantity}</span><button aria-label={`Increase ${item.productName} quantity`} className="secondary-button h-10 w-10 p-0" disabled={isLoading} onClick={()=>void act(()=>update(item.cartItemId,item.quantity+1))}>+</button><button className="ml-2 text-sm font-semibold text-red-700" disabled={isLoading} onClick={()=>void act(()=>remove(item.cartItemId))}>Remove</button></div></div><p className="text-lg font-bold sm:text-right">{formatINR(item.lineTotalPaise)}</p></article>)}</div><section className="mt-8 ml-auto max-w-md rounded-2xl border border-slate-200 bg-white p-6"><div className="flex justify-between text-xl font-bold"><span>Subtotal</span><span>{formatINR(cart.subtotalPaise)}</span></div><p className="mt-3 text-sm text-slate-600">Shipping and final totals are calculated at checkout in a later step.</p></section></>}
  </main>}
