'use client';
import { useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/features/auth/auth-provider';
import { useCart } from '@/features/cart/cart-provider';
import { formatINR } from '@/lib/format-money';
import type { ProductVariant, StockStatus } from '@/types/catalog';
const labels: Record<StockStatus,string> = { IN_STOCK:'In stock',LOW_STOCK:'Low stock',OUT_OF_STOCK:'Out of stock' };
const displayValue = (value: unknown) => typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean' ? String(value) : JSON.stringify(value);
export function VariantSelector({ variants }: { variants: ProductVariant[] }) {
  const active = useMemo(() => variants.filter((variant) => variant.isActive),[variants]); const [selectedId,setSelectedId] = useState(active[0]?.id ?? ''); const selected = active.find((variant) => variant.id === selectedId) ?? active[0];
  const [quantity,setQuantity]=useState(1); const [message,setMessage]=useState<string|null>(null); const [pending,setPending]=useState(false); const router=useRouter(); const {isAuthenticated}=useAuth(); const {add,cart}=useCart();
  if (!selected) return <div className="rounded-xl bg-red-50 p-4 text-red-800">No purchasable variants are currently available.</div>;
  const submit=async()=>{if(!isAuthenticated){router.push('/login');return;}setPending(true);setMessage(null);try{await add(selected.id,quantity);setMessage('Added to cart.');}catch(error){setMessage(error instanceof Error?error.message:'Unable to add item.');}finally{setPending(false)}};
  return <div><fieldset><legend className="text-sm font-semibold text-slate-900">Choose a variant</legend><div className="mt-3 grid gap-3 sm:grid-cols-2">{active.map((variant) => <label key={variant.id} className={`cursor-pointer rounded-xl border p-4 transition focus-within:ring-2 focus-within:ring-blue-600 ${selected.id === variant.id ? 'border-blue-700 bg-blue-50' : 'border-slate-300 bg-white'}`}><input type="radio" name="variant" value={variant.id} checked={selected.id === variant.id} onChange={() => setSelectedId(variant.id)} className="sr-only"/><span className="font-semibold">{variant.name}</span>{Object.entries(variant.attributes).length > 0 && <dl className="mt-2 space-y-1 text-sm text-slate-600">{Object.entries(variant.attributes).map(([key,value]) => <div key={key} className="flex gap-1"><dt className="capitalize">{key}:</dt><dd>{displayValue(value)}</dd></div>)}</dl>}<span className={`mt-2 block text-sm ${variant.stockStatus === 'OUT_OF_STOCK' ? 'text-red-700' : variant.stockStatus === 'LOW_STOCK' ? 'text-amber-700' : 'text-emerald-700'}`}>{labels[variant.stockStatus]}</span></label>)}</div></fieldset><div className="mt-6 border-t border-slate-200 pt-6"><p className="text-3xl font-bold">{formatINR(selected.retailPricePaise)}</p><p className={`mt-2 font-medium ${selected.stockStatus === 'OUT_OF_STOCK' ? 'text-red-700' : selected.stockStatus === 'LOW_STOCK' ? 'text-amber-700' : 'text-emerald-700'}`}>{labels[selected.stockStatus]}</p>{cart?.pricingMode==='WHOLESALE'&&<p className="mt-2 text-sm">Minimum wholesale quantity: {selected.wholesaleMinQty}</p>}<label className="mt-4 block text-sm font-medium">Quantity<input className="form-input mt-1 w-28" type="number" min="1" value={quantity} onChange={(event)=>setQuantity(Math.max(1,Number.parseInt(event.target.value,10)||1))}/></label><p className="mt-4 text-sm text-slate-600">Wholesale pricing is applied securely for approved accounts.</p>{message&&<p role="status" className="mt-3 text-sm">{message}</p>}<button type="button" disabled={pending||selected.stockStatus==='OUT_OF_STOCK'} onClick={()=>void submit()} className="primary-button mt-6">{pending?'Adding…':'Add to Cart'}</button></div></div>;
}
