import 'dotenv/config';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { test } from 'node:test';
import pg from 'pg';
const base='http://localhost:4000/api/v1', marker=`cart-${Date.now()}-${Math.random().toString(16).slice(2)}`, password='correct horse battery staple';
const emails={admin:`${marker}-admin@example.com`,retail:`${marker}-retail@example.com`,other:`${marker}-other@example.com`,wholesale:`${marker}-wholesale@example.com`};
const pool=new pg.Pool({connectionString:process.env.DATABASE_URL});let api,adminToken,retailToken,otherToken,wholesaleToken,productId,variantId,categoryId,itemId;
const request=(path,{method='GET',token,body}={})=>fetch(base+path,{method,headers:{...(token&&{authorization:`Bearer ${token}`}),...(body&&{'content-type':'application/json'})},body:body&&JSON.stringify(body)});
const body=async r=>r.json();
async function stop(){if(!api||api.exitCode!==null)return;const exited=new Promise(resolve=>api.once('exit',resolve));api.kill();const ok=await Promise.race([exited.then(()=>true),new Promise(resolve=>setTimeout(()=>resolve(false),2000))]);if(!ok){api.kill('SIGKILL');await exited;}}
async function cleanup(){await pool.query('DELETE FROM "Cart" WHERE "userId" IN (SELECT "id" FROM "User" WHERE "email" LIKE $1)',[`${marker}%`]);await pool.query('DELETE FROM "Inventory" WHERE "variantId" IN (SELECT "id" FROM "ProductVariant" WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "slug" LIKE $1))',[`${marker}%`]);await pool.query('DELETE FROM "ProductVariant" WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "slug" LIKE $1)',[`${marker}%`]);await pool.query('DELETE FROM "ProductCategory" WHERE "productId" IN (SELECT "id" FROM "Product" WHERE "slug" LIKE $1)',[`${marker}%`]);await pool.query('DELETE FROM "Product" WHERE "slug" LIKE $1',[`${marker}%`]);await pool.query('DELETE FROM "Category" WHERE "slug" LIKE $1',[`${marker}%`]);await pool.query('DELETE FROM "AdminAuditLog" WHERE "adminUserId" IN (SELECT "id" FROM "User" WHERE "email" LIKE $1)',[`${marker}%`]);await pool.query('DELETE FROM "User" WHERE "email" LIKE $1',[`${marker}%`]);}
test('secure retail and wholesale cart',async suite=>{await cleanup();api=spawn(process.execPath,['dist/main.js'],{stdio:'ignore',env:{...process.env,NODE_ENV:'test'}});for(let i=0;i<40;i++){try{if((await request('/health')).ok)break}catch{}await new Promise(r=>setTimeout(r,200));}
try{
await suite.test('fixtures',async()=>{for(const [key,email] of Object.entries(emails)){const r=await request('/auth/register',{method:'POST',body:{email,password,firstName:'Cart',lastName:key}});assert.equal(r.status,201);const token=(await body(r)).accessToken;if(key==='admin')adminToken=token;if(key==='retail')retailToken=token;if(key==='other')otherToken=token;if(key==='wholesale')wholesaleToken=token;}await pool.query('UPDATE "User" SET "role"=$1 WHERE "email"=$2',['ADMIN',emails.admin]);await pool.query('UPDATE "User" SET "accountType"=$1,"wholesaleStatus"=$2 WHERE "email"=$3',['WHOLESALE','APPROVED',emails.wholesale]);let r=await request('/admin/categories',{method:'POST',token:adminToken,body:{name:`${marker} category`}});categoryId=(await body(r)).id;r=await request('/admin/products',{method:'POST',token:adminToken,body:{name:`${marker} product`,categoryIds:[categoryId],variants:[{sku:`${marker}-sku`,name:'Bulk pack',attributes:{pack:'Standard'},retailPricePaise:1000,wholesalePricePaise:700,wholesaleMinQty:5,stockQuantity:8,reorderLevel:2}]}});const product=await body(r);productId=product.id;variantId=product.variants[0].id;});
await suite.test('authentication and tampering',async()=>{assert.equal((await request('/cart')).status,401);assert.equal((await request('/cart/items',{method:'POST',body:{variantId,quantity:1}})).status,401);assert.equal((await request('/cart/items',{method:'POST',token:retailToken,body:{variantId,quantity:1,unitPricePaise:1,lineTotalPaise:1}})).status,400);assert.equal((await request('/cart/pricing-mode',{method:'PATCH',token:retailToken,body:{pricingMode:'WHOLESALE'}})).status,403);});
await suite.test('retail add, price, merge and subtotal',async()=>{let r=await request('/cart/items',{method:'POST',token:retailToken,body:{variantId,quantity:2}});let cart=await body(r);assert.equal(cart.items[0].unitPricePaise,1000);assert.equal(cart.subtotalPaise,2000);itemId=cart.items[0].cartItemId;r=await request('/cart/items',{method:'POST',token:retailToken,body:{variantId,quantity:1}});cart=await body(r);assert.equal(cart.items.length,1);assert.equal(cart.items[0].quantity,3);});
await suite.test('ownership, stock and quantity update',async()=>{assert.equal((await request(`/cart/items/${itemId}`,{method:'PATCH',token:otherToken,body:{quantity:2}})).status,404);await pool.query('UPDATE "Inventory" SET "reservedQuantity"=5 WHERE "variantId"=$1',[variantId]);assert.equal((await request(`/cart/items/${itemId}`,{method:'PATCH',token:retailToken,body:{quantity:4}})).status,409);let r=await request(`/cart/items/${itemId}`,{method:'PATCH',token:retailToken,body:{quantity:3}});assert.equal(r.status,200);assert.equal(JSON.stringify(await body(r)).includes('reservedQuantity'),false);await pool.query('UPDATE "Inventory" SET "reservedQuantity"=0 WHERE "variantId"=$1',[variantId]);});
await suite.test('wholesale MOQ, price and mode switch',async()=>{let r=await request('/cart/items',{method:'POST',token:wholesaleToken,body:{variantId,quantity:1}});let cart=await body(r);const wholesaleItemId=cart.items[0].cartItemId;assert.equal((await request('/cart/pricing-mode',{method:'PATCH',token:wholesaleToken,body:{pricingMode:'WHOLESALE'}})).status,400);await request(`/cart/items/${wholesaleItemId}`,{method:'PATCH',token:wholesaleToken,body:{quantity:5}});r=await request('/cart/pricing-mode',{method:'PATCH',token:wholesaleToken,body:{pricingMode:'WHOLESALE'}});cart=await body(r);assert.equal(cart.items[0].unitPricePaise,700);await request('/cart',{method:'DELETE',token:wholesaleToken});assert.equal((await request('/cart/items',{method:'POST',token:wholesaleToken,body:{variantId,quantity:4}})).status,400);r=await request('/cart/items',{method:'POST',token:wholesaleToken,body:{variantId,quantity:5}});cart=await body(r);assert.equal(cart.pricingMode,'WHOLESALE');assert.equal(cart.items[0].unitPricePaise,700);assert.equal(cart.items[0].lineTotalPaise,3500);r=await request('/cart/pricing-mode',{method:'PATCH',token:wholesaleToken,body:{pricingMode:'RETAIL'}});assert.equal((await body(r)).items[0].unitPricePaise,1000);});
await suite.test('remove and clear',async()=>{assert.equal((await request(`/cart/items/${itemId}`,{method:'DELETE',token:retailToken})).status,200);await request('/cart/items',{method:'POST',token:retailToken,body:{variantId,quantity:1}});assert.equal((await request('/cart',{method:'DELETE',token:retailToken})).status,200);assert.equal((await body(await request('/cart',{token:retailToken}))).items.length,0);});
}finally{await stop();await cleanup();await pool.end();}});
