

import'dotenv/config';import assert from'node:assert/strict';import{spawn}from'node:child_process';import{test}from'node:test';import pg from'pg';const port=4012,base=`http://localhost:${port}/api/v1`,m=`step11-${Date.now()}`,pool=new pg.Pool({connectionString:process.env.DATABASE_URL});let api,a,b,admin,uidA,uidB,adminId,addressId,applicationId;const req=(p,{token,method='GET',body}={})=>fetch(base+p,{method,headers:{...(token&&{authorization:`Bearer ${token}`}),...(body&&{'content-type':'application/json'})},body:body&&JSON.stringify(body)});const register=async suffix=>{const r=await req('/auth/register',{method:'POST',body:{email:`${m}-${suffix}@example.com`,password:'correct horse battery staple',firstName:'Step',lastName:suffix}});assert.equal(r.status,201);return(await r.json()).accessToken};
test('Step 11 customer management security',async s=>{api=spawn(process.execPath,['dist/main.js'],{stdio:'ignore',env:{...process.env,PORT:String(port),NODE_ENV:'test'}});for(let i=0;i<80;i++){try{if((await req('/health')).ok)break}catch{}await new Promise(r=>setTimeout(r,200))}try{
await s.test('fixtures and admin security',async()=>{a=await register('a');b=await register('b');admin=await register('admin');const users=await pool.query('SELECT id,email FROM "User" WHERE email LIKE $1',[`${m}%`]);uidA=users.rows.find(x=>x.email.includes('-a@')).id;uidB=users.rows.find(x=>x.email.includes('-b@')).id;adminId=users.rows.find(x=>x.email.includes('-admin@')).id;await pool.query('UPDATE "User" SET role=$1 WHERE id=$2',['ADMIN',adminId]);assert.equal((await req('/admin/customers',{token:a})).status,403);assert.equal((await req('/admin/customers',{token:admin})).status,200);assert.equal((await req('/admin/customers')).status,401)});
await s.test('safe profile mapping and mass assignment',async()=>{let r=await req('/users/me',{token:a}),j=await r.json();assert.equal(j.email,`${m}-a@example.com`);assert.equal('passwordHash'in j,false);r=await req('/users/me',{method:'PATCH',token:a,body:{firstName:'Updated',phone:'9876543210'}});assert.equal(r.status,200);assert.equal((await r.json()).firstName,'Updated');assert.equal((await req('/users/me',{method:'PATCH',token:a,body:{firstName:'Bad',role:'ADMIN',accountType:'WHOLESALE',wholesaleStatus:'APPROVED'}})).status,400)});
await s.test('address CRUD, default transaction and IDOR',async()=>{let r=await req('/addresses',{method:'POST',token:a,body:{label:'Home',fullName:'Step A',phone:'9876543210',addressLine1:'1 Test Road',city:'Delhi',state:'Delhi',postalCode:'110001'}});assert.equal(r.status,201);const j=await r.json();addressId=j.id;assert.equal(j.countryCode,'IN');assert.equal(j.isDefault,true);for(const[method,path]of[['GET',`/addresses/${addressId}`],['PATCH',`/addresses/${addressId}`],['DELETE',`/addresses/${addressId}`],['POST',`/addresses/${addressId}/default`]])assert.equal((await req(path,{method,token:b,body:method==='PATCH'?{label:'Stolen'}:undefined})).status,404);assert.equal((await req(`/addresses/${addressId}`,{method:'PATCH',token:a,body:{label:'Office'}})).status,200);assert.equal((await req(`/addresses/${addressId}/default`,{method:'POST',token:a})).status,201)});
await s.test('application validation and duplicate protection',async()=>{const payload={businessName:'Test Business',businessType:'Retailer',gstin:'22AAAAA0000A1Z5',businessAddress:'2 Business Road',notes:'Review me'};let r=await req('/wholesale/applications',{method:'POST',token:a,body:payload});assert.equal(r.status,201);applicationId=(await r.json()).id;assert.equal((await req('/wholesale/applications',{method:'POST',token:a,body:payload})).status,409);assert.equal((await req('/wholesale/applications',{method:'POST',token:b,body:{...payload,status:'APPROVED'}})).status,400);assert.equal((await req(`/admin/wholesale/applications/${applicationId}/approve`,{method:'POST',token:a})).status,403)});
await s.test('approval, repeated-review and wholesale pricing',async()=>{assert.equal((await req(`/admin/wholesale/applications/${applicationId}/approve`,{method:'POST',token:admin})).status,201);assert.equal((await req(`/admin/wholesale/applications/${applicationId}/approve`,{method:'POST',token:admin})).status,409);const user=(await pool.query('SELECT "accountType","wholesaleStatus" FROM "User" WHERE id=$1',[uidA])).rows[0];assert.deepEqual(user,{accountType:'WHOLESALE',wholesaleStatus:'APPROVED'});assert.equal((await req('/cart/pricing-mode',{method:'PATCH',token:a,body:{pricingMode:'WHOLESALE'}})).status,200)});
await s.test('rejection and wholesale denial',async()=>{const payload={businessName:'Rejected Business',businessType:'Retailer',businessAddress:'3 Business Road'};let r=await req('/wholesale/applications',{method:'POST',token:b,body:payload});const id=(await r.json()).id;assert.equal((await req(`/admin/wholesale/applications/${id}/reject`,{method:'POST',token:admin,body:{reason:'Insufficient documents'}})).status,201);const user=(await pool.query('SELECT "accountType","wholesaleStatus" FROM "User" WHERE id=$1',[uidB])).rows[0];assert.deepEqual(user,{accountType:'RETAIL',wholesaleStatus:'REJECTED'});assert.equal((await req('/cart/pricing-mode',{method:'PATCH',token:b,body:{pricingMode:'WHOLESALE'}})).status,403)});
await s.test('deactivation, activation, sessions and audit',async()=>{assert.equal((await req(`/admin/customers/${uidA}/status`,{method:'PATCH',token:admin,body:{isActive:false}})).status,200);assert.equal((await req('/users/me',{token:a})).status,401);assert.equal((await req('/auth/login',{method:'POST',body:{email:`${m}-a@example.com`,password:'correct horse battery staple'}})).status,401);assert.equal((await req(`/admin/customers/${uidA}/status`,{method:'PATCH',token:admin,body:{isActive:true}})).status,200);assert.equal((await req('/auth/login',{method:'POST',body:{email:`${m}-a@example.com`,password:'correct horse battery staple'}})).status,200);const audit=await pool.query('SELECT action FROM "AdminAuditLog" WHERE "adminUserId"=$1 AND "entityId" IN($2,$3) ORDER BY "createdAt"',[adminId,uidA,applicationId]);assert.deepEqual(new Set(audit.rows.map(x=>x.action)),new Set(['WHOLESALE_APPROVE','CUSTOMER_DEACTIVATE','CUSTOMER_ACTIVATE']))});
}finally{if(api)api.kill('SIGKILL');await pool.query('DELETE FROM "AdminAuditLog" WHERE "adminUserId" IN(SELECT id FROM "User" WHERE email LIKE $1)',[`${m}%`]);await pool.query('DELETE FROM "WholesaleApplication" WHERE "userId" IN($1,$2)',[uidA,uidB]).catch(()=>{});await pool.query('DELETE FROM "User" WHERE email LIKE $1',[`${m}%`]);await pool.end()}});


