import { Transform, Type } from 'class-transformer';import { ArrayMaxSize, ArrayMinSize, IsBoolean, IsDateString, IsEnum, IsInt, IsISO31661Alpha2, IsOptional, IsString, IsUrl, IsUUID, Length, Max, MaxLength, Min, ValidateNested } from 'class-validator';import { PricingMode, ReturnStatus, ShipmentStatus } from '../../../generated/prisma/client';const trim=({value}:{value:unknown})=>typeof value==='string'?value.trim():value;
export class ShippingRuleDto{@Transform(trim)@IsString()@Length(1,150)name!:string;@IsOptional()@IsISO31661Alpha2()countryCode='IN';@Transform(trim)@IsOptional()@IsString()@MaxLength(100)stateCode?:string;@IsOptional()@IsEnum(PricingMode)pricingMode?:PricingMode;@Type(()=>Number)@IsInt()@Min(0)minSubtotalPaise=0;@Type(()=>Number)@IsOptional()@IsInt()@Min(0)maxSubtotalPaise?:number;@Type(()=>Number)@IsInt()@Min(0)shippingPaise!:number;@Type(()=>Number)@IsInt()@Min(0)priority=0;@IsOptional()@IsBoolean()isActive=true;}
export class UpdateShippingRuleDto{@Transform(trim)@IsOptional()@IsString()@Length(1,150)name?:string;@IsOptional()@IsISO31661Alpha2()countryCode?:string;@Transform(trim)@IsOptional()@IsString()@MaxLength(100)stateCode?:string;@IsOptional()@IsEnum(PricingMode)pricingMode?:PricingMode;@Type(()=>Number)@IsOptional()@IsInt()@Min(0)minSubtotalPaise?:number;@Type(()=>Number)@IsOptional()@IsInt()@Min(0)maxSubtotalPaise?:number;@Type(()=>Number)@IsOptional()@IsInt()@Min(0)shippingPaise?:number;@Type(()=>Number)@IsOptional()@IsInt()@Min(0)priority?:number;@IsOptional()@IsBoolean()isActive?:boolean;}
export class ShipmentDto{@Transform(trim)@IsString()@Length(1,100)carrierName!:string;@Transform(trim)@IsOptional()@IsString()@MaxLength(150)trackingNumber?:string;@IsOptional()@IsUrl({require_protocol:true})@MaxLength(500)trackingUrl?:string;}
export class UpdateShipmentDto{@Transform(trim)@IsOptional()@IsString()@Length(1,100)carrierName?:string;@Transform(trim)@IsOptional()@IsString()@MaxLength(150)trackingNumber?:string;@IsOptional()@IsUrl({require_protocol:true})@MaxLength(500)trackingUrl?:string;@IsOptional()@IsEnum(ShipmentStatus)status?:ShipmentStatus;}
export class ReturnLineDto{@IsUUID()orderItemId!:string;@Type(()=>Number)@IsInt()@Min(1)quantity!:number;@Transform(trim)@IsOptional()@IsString()@MaxLength(500)reason?:string;}
export class CreateReturnDto{@Transform(trim)@IsString()@Length(1,500)reason!:string;@Transform(trim)@IsOptional()@IsString()@MaxLength(1000)customerNote?:string;@ArrayMinSize(1)@ArrayMaxSize(100)@ValidateNested({each:true})@Type(()=>ReturnLineDto)items!:ReturnLineDto[];}
export class RejectReturnDto{@Transform(trim)@IsString()@Length(1,1000)reason!:string;}
export class RestockLineDto{@IsUUID()returnItemId!:string;@Type(()=>Number)@IsInt()@Min(1)quantity!:number;}
export class RestockDto{@ArrayMinSize(1)@ArrayMaxSize(100)@ValidateNested({each:true})@Type(()=>RestockLineDto)items!:RestockLineDto[];}
export class ReturnQueryDto{@Type(()=>Number)@IsInt()@Min(1)page=1;@Type(()=>Number)@IsInt()@Min(1)@Max(100)limit=20;@IsOptional()@IsEnum(ReturnStatus)status?:ReturnStatus;@Transform(trim)@IsOptional()@IsString()@MaxLength(100)search?:string;@IsOptional()@IsDateString()dateFrom?:string;@IsOptional()@IsDateString()dateTo?:string;}
